set -e

./runfile.sh UniMath/Foundations/Init.v
./runfile.sh UniMath/Foundations/Preamble.v
./runfile.sh UniMath/Foundations/PartA.v
./runfile.sh UniMath/Foundations/PartB.v
./runfile.sh UniMath/Foundations/UnivalenceAxiom.v
./runfile.sh UniMath/Foundations/PartC.v
./runfile.sh UniMath/Foundations/PartD.v
./runfile.sh UniMath/Foundations/UnivalenceAxiom2.v
./runfile.sh UniMath/Foundations/Propositions.v
./runfile.sh UniMath/Foundations/Sets.v
./runfile.sh UniMath/Foundations/NaturalNumbers.v
./runfile.sh UniMath/Foundations/Tests.v
./runfile.sh UniMath/Foundations/HLevels.v
./runfile.sh UniMath/Foundations/All.v
./runfile.sh UniMath/MoreFoundations/Bool.v
./runfile.sh UniMath/MoreFoundations/Test.v
./runfile.sh UniMath/MoreFoundations/WeakEquivalences.v
./runfile.sh UniMath/MoreFoundations/Tactics.v
./runfile.sh UniMath/MoreFoundations/PartA.v
./runfile.sh UniMath/MoreFoundations/PathsOver.v
./runfile.sh UniMath/MoreFoundations/Nat.v
./runfile.sh UniMath/MoreFoundations/Notations.v
./runfile.sh UniMath/MoreFoundations/AlternativeProofs.v
./runfile.sh UniMath/MoreFoundations/Subposets.v
./runfile.sh UniMath/MoreFoundations/DoubleNegation.v
./runfile.sh UniMath/MoreFoundations/DecidablePropositions.v
./runfile.sh UniMath/MoreFoundations/Propositions.v
./runfile.sh UniMath/MoreFoundations/NullHomotopies.v
./runfile.sh UniMath/MoreFoundations/Interval.v
./runfile.sh UniMath/MoreFoundations/NegativePropositions.v
./runfile.sh UniMath/MoreFoundations/Sets.v
./runfile.sh UniMath/MoreFoundations/Orders.v
./runfile.sh UniMath/MoreFoundations/Equivalences.v
./runfile.sh UniMath/MoreFoundations/MoreEquivalences.v
./runfile.sh UniMath/MoreFoundations/QuotientSet.v
./runfile.sh UniMath/MoreFoundations/Subtypes.v
./runfile.sh UniMath/MoreFoundations/AxiomOfChoice.v
./runfile.sh UniMath/MoreFoundations/StructureIdentity.v
./runfile.sh UniMath/MoreFoundations/Univalence.v
./runfile.sh UniMath/MoreFoundations/NoInjectivePairing.v
./runfile.sh UniMath/MoreFoundations/PartD.v
./runfile.sh UniMath/MoreFoundations/All.v
./runfile.sh UniMath/Combinatorics/StandardFiniteSets.v
./runfile.sh UniMath/Combinatorics/Vectors.v
./runfile.sh UniMath/Combinatorics/VectorsTests.v
./runfile.sh UniMath/Combinatorics/Lists.v
./runfile.sh UniMath/Combinatorics/FiniteSets.v
./runfile.sh UniMath/Combinatorics/KFiniteTypes.v
./runfile.sh UniMath/Combinatorics/KFiniteSubtypes.v
./runfile.sh UniMath/Combinatorics/Graph.v
./runfile.sh UniMath/Combinatorics/CGraph.v
./runfile.sh UniMath/Combinatorics/GraphPaths.v
./runfile.sh UniMath/Combinatorics/Equivalence_Relations.v
./runfile.sh UniMath/Combinatorics/OrderedSets.v
./runfile.sh UniMath/Combinatorics/WellFoundedRelations.v
./runfile.sh UniMath/Combinatorics/WellOrderedSets.v
./runfile.sh UniMath/Combinatorics/ZFstructures.v
./runfile.sh UniMath/Combinatorics/FiniteSequences.v
./runfile.sh UniMath/Combinatorics/BoundedSearch.v
./runfile.sh UniMath/Combinatorics/MetricTree.v
./runfile.sh UniMath/Combinatorics/Tests.v
./runfile.sh UniMath/Combinatorics/DecSet.v
./runfile.sh UniMath/Combinatorics/Maybe.v
./runfile.sh UniMath/Combinatorics/MoreLists.v
./runfile.sh UniMath/Combinatorics/Tuples.v
./runfile.sh UniMath/Combinatorics/All.v
./runfile.sh UniMath/Algebra/BinaryOperations.v
./runfile.sh UniMath/Algebra/Monoids.v
./runfile.sh UniMath/Algebra/Groups.v
./runfile.sh UniMath/Algebra/GroupAction.v
./runfile.sh UniMath/Algebra/RigsAndRings.v
./runfile.sh UniMath/Algebra/RigsAndRings/Ideals.v
./runfile.sh UniMath/Algebra/Domains_and_Fields.v
./runfile.sh UniMath/Algebra/DivisionRig.v
./runfile.sh UniMath/Algebra/Apartness.v
./runfile.sh UniMath/Algebra/ConstructiveStructures.v
./runfile.sh UniMath/Algebra/Archimedean.v
./runfile.sh UniMath/Algebra/IteratedBinaryOperations.v
./runfile.sh UniMath/Algebra/Free_Monoids_and_Groups.v
./runfile.sh UniMath/Algebra/Tests.v
./runfile.sh UniMath/Algebra/Modules/Core.v
./runfile.sh UniMath/Algebra/Modules/Submodule.v
./runfile.sh UniMath/Algebra/Modules/Multimodules.v
./runfile.sh UniMath/Algebra/Modules/Examples.v
./runfile.sh UniMath/Algebra/Modules/Quotient.v
./runfile.sh UniMath/Algebra/Modules.v
./runfile.sh UniMath/Algebra/Matrix.v
./runfile.sh UniMath/Algebra/Universal/HVectors.v
./runfile.sh UniMath/Algebra/Universal/SortedTypes.v
./runfile.sh UniMath/Algebra/Universal/Signatures.v
./runfile.sh UniMath/Algebra/Universal/Algebras.v
./runfile.sh UniMath/Algebra/Universal/Terms.v
./runfile.sh UniMath/Algebra/Universal/TermAlgebras.v
./runfile.sh UniMath/Algebra/Universal/VTerms.v
./runfile.sh UniMath/Algebra/Universal/FreeAlgebras.v
./runfile.sh UniMath/Algebra/Universal/Equations.v
./runfile.sh UniMath/Algebra/Universal/EqAlgebras.v
./runfile.sh UniMath/Algebra/Universal/Examples/Nat.v
./runfile.sh UniMath/Algebra/Universal/Examples/Bool.v
./runfile.sh UniMath/Algebra/Universal/Examples/Monoid.v
./runfile.sh UniMath/Algebra/Universal/Examples/Group.v
./runfile.sh UniMath/Algebra/Universal/Examples/ListDataType.v
./runfile.sh UniMath/Algebra/Universal/Examples/Tests.v
./runfile.sh UniMath/Algebra/Universal.v
./runfile.sh UniMath/Algebra/GaussianElimination/Auxiliary.v
./runfile.sh UniMath/Algebra/GaussianElimination/Vectors.v
./runfile.sh UniMath/Algebra/GaussianElimination/Matrices.v
./runfile.sh UniMath/Algebra/GaussianElimination/RowOps.v
./runfile.sh UniMath/Algebra/GaussianElimination/Elimination.v
./runfile.sh UniMath/Algebra/GaussianElimination/Corollaries.v
./runfile.sh UniMath/Algebra/GaussianElimination/Tests.v
./runfile.sh UniMath/Algebra/All.v
./runfile.sh UniMath/Tactics/EnsureStructuredProofs.v
./runfile.sh UniMath/Tactics/Utilities.v
./runfile.sh UniMath/Tactics/Monoids_Tactics.v
./runfile.sh UniMath/Tactics/Abmonoids_Tactics.v
./runfile.sh UniMath/Tactics/Groups_Tactics.v
./runfile.sh UniMath/Tactics/Nat_Tactics.v
./runfile.sh UniMath/Tactics/All.v
./runfile.sh UniMath/NumberSystems/NaturalNumbersAlgebra.v
./runfile.sh UniMath/NumberSystems/NaturalNumbers_le_Inductive.v
./runfile.sh UniMath/NumberSystems/Integers.v
./runfile.sh UniMath/NumberSystems/RationalNumbers.v
./runfile.sh UniMath/NumberSystems/Tests.v
./runfile.sh UniMath/NumberSystems/All.v
./runfile.sh UniMath/SyntheticHomotopyTheory/Coproduct.v
./runfile.sh UniMath/SyntheticHomotopyTheory/Halfline.v
./runfile.sh UniMath/SyntheticHomotopyTheory/AffineLine.v
./runfile.sh UniMath/SyntheticHomotopyTheory/Circle.v
./runfile.sh UniMath/SyntheticHomotopyTheory/Circle2.v
./runfile.sh UniMath/SyntheticHomotopyTheory/Test.v
./runfile.sh UniMath/SyntheticHomotopyTheory/All.v
./runfile.sh UniMath/PAdics/lemmas.v
./runfile.sh UniMath/PAdics/fps.v
./runfile.sh UniMath/PAdics/frac.v
./runfile.sh UniMath/PAdics/z_mod_p.v
./runfile.sh UniMath/PAdics/padics.v
./runfile.sh UniMath/PAdics/All.v
./runfile.sh UniMath/OrderTheory/Posets/Basics.v
./runfile.sh UniMath/OrderTheory/Posets/MonotoneFunctions.v
./runfile.sh UniMath/OrderTheory/Posets/PosetSum.v
./runfile.sh UniMath/OrderTheory/Posets/PointedPosets.v
./runfile.sh UniMath/OrderTheory/Posets/LiftPoset.v
./runfile.sh UniMath/OrderTheory/Posets/QuotientPoset.v
./runfile.sh UniMath/OrderTheory/Posets.v
./runfile.sh UniMath/OrderTheory/Lattice/Lattice.v
./runfile.sh UniMath/OrderTheory/Lattice/Bounded.v
./runfile.sh UniMath/OrderTheory/Lattice/Complement.v
./runfile.sh UniMath/OrderTheory/Lattice/Distributive.v
./runfile.sh UniMath/OrderTheory/Lattice/Heyting.v
./runfile.sh UniMath/OrderTheory/Lattice/Boolean.v
./runfile.sh UniMath/OrderTheory/Lattice/Examples/Bool.v
./runfile.sh UniMath/OrderTheory/Lattice/Examples/Subsets.v
./runfile.sh UniMath/OrderTheory/DCPOs/Core/DirectedSets.v
./runfile.sh UniMath/OrderTheory/DCPOs/Core/Basics.v
./runfile.sh UniMath/OrderTheory/DCPOs/Core/WayBelow.v
./runfile.sh UniMath/OrderTheory/DCPOs/Basis/Continuous.v
./runfile.sh UniMath/OrderTheory/DCPOs/Basis/Algebraic.v
./runfile.sh UniMath/OrderTheory/DCPOs/Core/ScottTopology.v
./runfile.sh UniMath/OrderTheory/DCPOs/Core/IntrinsicApartness.v
./runfile.sh UniMath/OrderTheory/DCPOs/Core/ScottContinuous.v
./runfile.sh UniMath/OrderTheory/DCPOs/Basis/Basis.v
./runfile.sh UniMath/OrderTheory/DCPOs/Basis/CompactBasis.v
./runfile.sh UniMath/OrderTheory/DCPOs/Elements/Sharp.v
./runfile.sh UniMath/OrderTheory/DCPOs/Elements/Maximal.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/Unit.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/Propositions.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/Discrete.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/SubDCPO.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/Fixpoints.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/Equalizers.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/BinaryProducts.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/Products.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/BinarySums.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/Sums.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/IdealCompletion.v
./runfile.sh UniMath/OrderTheory/DCPOs/Core/FubiniTheorem.v
./runfile.sh UniMath/OrderTheory/DCPOs/Core/CoordinateContinuity.v
./runfile.sh UniMath/OrderTheory/DCPOs/Examples/Exponentials.v
./runfile.sh UniMath/OrderTheory/DCPOs/FixpointTheorems/LeastFixpoint.v
./runfile.sh UniMath/OrderTheory/DCPOs/FixpointTheorems/Pataraia.v
./runfile.sh UniMath/OrderTheory/DCPOs/AlternativeDefinitions/Dcpo.v
./runfile.sh UniMath/OrderTheory/DCPOs/AlternativeDefinitions/FixedPointTheorems.v
./runfile.sh UniMath/CategoryTheory/Core/Categories.v
./runfile.sh UniMath/CategoryTheory/Core/Isos.v
./runfile.sh UniMath/CategoryTheory/Core/Univalence.v
./runfile.sh UniMath/CategoryTheory/Core/TwoCategories.v
./runfile.sh UniMath/CategoryTheory/Core/TransportMorphisms.v
./runfile.sh UniMath/CategoryTheory/Core/Functors.v
./runfile.sh UniMath/CategoryTheory/Core/NaturalTransformations.v
./runfile.sh UniMath/CategoryTheory/Core/Setcategories.v
./runfile.sh UniMath/CategoryTheory/Core/EssentiallyAlgebraic.v
./runfile.sh UniMath/CategoryTheory/Core/Prelude.v
./runfile.sh UniMath/CategoryTheory/FunctorCategory.v
./runfile.sh UniMath/CategoryTheory/whiskering.v
./runfile.sh UniMath/CategoryTheory/BicatOfCatsElementary.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Core.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Isos.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Functors.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/NaturalTransformations.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Univalence.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/DisplayedFunctorEq.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Total.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Fiber.v
./runfile.sh UniMath/CategoryTheory/opp_precat.v
./runfile.sh UniMath/CategoryTheory/OppositeCategory/Core.v
./runfile.sh UniMath/CategoryTheory/Groupoids.v
./runfile.sh UniMath/CategoryTheory/ZigZag.v
./runfile.sh UniMath/CategoryTheory/ProductCategory.v
./runfile.sh UniMath/CategoryTheory/PrecategoryBinProduct.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/Core.v
./runfile.sh UniMath/CategoryTheory/CategorySum.v
./runfile.sh UniMath/CategoryTheory/Subcategory/Core.v
./runfile.sh UniMath/CategoryTheory/Subcategory/Full.v
./runfile.sh UniMath/CategoryTheory/Monics.v
./runfile.sh UniMath/CategoryTheory/Epis.v
./runfile.sh UniMath/CategoryTheory/SplitMonicsAndEpis.v
./runfile.sh UniMath/CategoryTheory/HomotopicalCategory.v
./runfile.sh UniMath/CategoryTheory/Adjunctions/Core.v
./runfile.sh UniMath/CategoryTheory/Monads/RelativeMonads.v
./runfile.sh UniMath/CategoryTheory/Monads/RelMonads_Coreflection.v
./runfile.sh UniMath/CategoryTheory/Monads/RelativeModules.v
./runfile.sh UniMath/CategoryTheory/Equivalences/Core.v
./runfile.sh UniMath/CategoryTheory/Equivalences/CompositesAndInverses.v
./runfile.sh UniMath/CategoryTheory/Equivalences/FullyFaithful.v
./runfile.sh UniMath/CategoryTheory/Subcategory/FullEquivalences.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/MonoEpiIso.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/Univalence.v
./runfile.sh UniMath/CategoryTheory/CategoriesWithBinOps.v
./runfile.sh UniMath/CategoryTheory/PrecategoriesWithAbgrops.v
./runfile.sh UniMath/CategoryTheory/covyoneda.v
./runfile.sh UniMath/CategoryTheory/limits/cones.v
./runfile.sh UniMath/CategoryTheory/limits/equalizers.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/colimits.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/limits.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/eqdiag.v
./runfile.sh UniMath/CategoryTheory/limits/coproducts.v
./runfile.sh UniMath/CategoryTheory/limits/products.v
./runfile.sh UniMath/CategoryTheory/limits/initial.v
./runfile.sh UniMath/CategoryTheory/limits/terminal.v
./runfile.sh UniMath/CategoryTheory/limits/zero.v
./runfile.sh UniMath/CategoryTheory/limits/bincoproducts.v
./runfile.sh UniMath/CategoryTheory/limits/binproducts.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/bincoproducts.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/Coproducts.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/binproducts.v
./runfile.sh UniMath/CategoryTheory/limits/pullbacks.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/initial.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/terminal.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/zero.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/pullbacks.v
./runfile.sh UniMath/CategoryTheory/limits/coequalizers.v
./runfile.sh UniMath/CategoryTheory/limits/kernels.v
./runfile.sh UniMath/CategoryTheory/limits/cokernels.v
./runfile.sh UniMath/CategoryTheory/PreAdditive.v
./runfile.sh UniMath/CategoryTheory/limits/pushouts.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/pushouts.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/equalizers.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/coequalizers.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/kernels.v
./runfile.sh UniMath/CategoryTheory/limits/graphs/cokernels.v
./runfile.sh UniMath/CategoryTheory/limits/cats/limits.v
./runfile.sh UniMath/CategoryTheory/limits/BinDirectSums.v
./runfile.sh UniMath/CategoryTheory/limits/FinOrdProducts.v
./runfile.sh UniMath/CategoryTheory/limits/FinOrdCoproducts.v
./runfile.sh UniMath/CategoryTheory/limits/Opp.v
./runfile.sh UniMath/CategoryTheory/limits/Preservation.v
./runfile.sh UniMath/CategoryTheory/limits/Ends.v
./runfile.sh UniMath/CategoryTheory/limits/Coends.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Binproducts.v
./runfile.sh UniMath/CategoryTheory/limits/Examples/CategoryProductLimits.v
./runfile.sh UniMath/CategoryTheory/limits/StandardDiagrams.v
./runfile.sh UniMath/CategoryTheory/limits/Filtered.v
./runfile.sh UniMath/CategoryTheory/IsoCommaCategory.v
./runfile.sh UniMath/CategoryTheory/limits/Examples/IsoCommaLimits.v
./runfile.sh UniMath/CategoryTheory/CommaCategories.v
./runfile.sh UniMath/CategoryTheory/NNO.v
./runfile.sh UniMath/CategoryTheory/Subcategory/Limits.v
./runfile.sh UniMath/CategoryTheory/EpiFacts.v
./runfile.sh UniMath/CategoryTheory/categories/Type/Core.v
./runfile.sh UniMath/CategoryTheory/categories/Type/MonoEpiIso.v
./runfile.sh UniMath/CategoryTheory/SimplicialSets.v
./runfile.sh UniMath/CategoryTheory/yoneda.v
./runfile.sh UniMath/CategoryTheory/FunctorCoalgebras.v
./runfile.sh UniMath/CategoryTheory/precomp_fully_faithful.v
./runfile.sh UniMath/CategoryTheory/precomp_ess_surj.v
./runfile.sh UniMath/CategoryTheory/PrecompEquivalence.v
./runfile.sh UniMath/CategoryTheory/UnitorsAndAssociatorsForEndofunctors.v
./runfile.sh UniMath/CategoryTheory/PointedFunctors.v
./runfile.sh UniMath/CategoryTheory/HorizontalComposition.v
./runfile.sh UniMath/CategoryTheory/PointedFunctorsComposition.v
./runfile.sh UniMath/CategoryTheory/ArrowCategory.v
./runfile.sh UniMath/CategoryTheory/RightKanExtension.v
./runfile.sh UniMath/CategoryTheory/coslicecat.v
./runfile.sh UniMath/CategoryTheory/catiso.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/CatIsoDisplayed.v
./runfile.sh UniMath/CategoryTheory/CategoryEquality.v
./runfile.sh UniMath/CategoryTheory/WeakEquivalences.v
./runfile.sh UniMath/CategoryTheory/rezk_completion.v
./runfile.sh UniMath/CategoryTheory/RezkCompletion.v
./runfile.sh UniMath/CategoryTheory/exponentials.v
./runfile.sh UniMath/CategoryTheory/slicecat.v
./runfile.sh UniMath/CategoryTheory/limits/pullbacks_slice_products_equiv.v
./runfile.sh UniMath/CategoryTheory/Additive.v
./runfile.sh UniMath/CategoryTheory/Abelian.v
./runfile.sh UniMath/CategoryTheory/category_binops.v
./runfile.sh UniMath/CategoryTheory/AbelianToAdditive.v
./runfile.sh UniMath/CategoryTheory/Morphisms.v
./runfile.sh UniMath/CategoryTheory/ExactCategories/ExactCategories.v
./runfile.sh UniMath/CategoryTheory/ExactCategories/Tests.v
./runfile.sh UniMath/CategoryTheory/ShortExactSequences.v
./runfile.sh UniMath/CategoryTheory/AdditiveFunctors.v
./runfile.sh UniMath/CategoryTheory/LocalizingClass.v
./runfile.sh UniMath/CategoryTheory/UnderCategories.v
./runfile.sh UniMath/CategoryTheory/Subobjects.v
./runfile.sh UniMath/CategoryTheory/SubobjectClassifier.v
./runfile.sh UniMath/CategoryTheory/Quotobjects.v
./runfile.sh UniMath/CategoryTheory/AbelianPushoutPullback.v
./runfile.sh UniMath/CategoryTheory/PseudoElements.v
./runfile.sh UniMath/CategoryTheory/FiveLemma.v
./runfile.sh UniMath/CategoryTheory/LatticeObject.v
./runfile.sh UniMath/CategoryTheory/Actions.v
./runfile.sh UniMath/CategoryTheory/PowerObject.v
./runfile.sh UniMath/CategoryTheory/ElementaryTopos.v
./runfile.sh UniMath/CategoryTheory/Adjunctions/Restriction.v
./runfile.sh UniMath/CategoryTheory/Adjunctions/Examples.v
./runfile.sh UniMath/CategoryTheory/Subcategory/Reflective.v
./runfile.sh UniMath/CategoryTheory/categories/CategoryOfSetCategories.v
./runfile.sh UniMath/CategoryTheory/limits/Examples/CategoryOfSetcategoriesLimits.v
./runfile.sh UniMath/CategoryTheory/categories/setwith2binops.v
./runfile.sh UniMath/CategoryTheory/categories/monoids.v
./runfile.sh UniMath/CategoryTheory/categories/abmonoids.v
./runfile.sh UniMath/CategoryTheory/categories/grs.v
./runfile.sh UniMath/CategoryTheory/categories/abgrs.v
./runfile.sh UniMath/CategoryTheory/categories/rigs.v
./runfile.sh UniMath/CategoryTheory/categories/commrigs.v
./runfile.sh UniMath/CategoryTheory/categories/rings.v
./runfile.sh UniMath/CategoryTheory/categories/commrings.v
./runfile.sh UniMath/CategoryTheory/categories/intdoms.v
./runfile.sh UniMath/CategoryTheory/categories/flds.v
./runfile.sh UniMath/CategoryTheory/categories/modules.v
./runfile.sh UniMath/CategoryTheory/categories/StandardCategories.v
./runfile.sh UniMath/CategoryTheory/categories/preorder_categories.v
./runfile.sh UniMath/CategoryTheory/limits/Examples/UnitCategoryLimits.v
./runfile.sh UniMath/CategoryTheory/categories/Type/Colimits.v
./runfile.sh UniMath/CategoryTheory/categories/Type/Limits.v
./runfile.sh UniMath/CategoryTheory/categories/Type/Structures.v
./runfile.sh UniMath/CategoryTheory/categories/Type/Univalence.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/Limits.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/Colimits.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/FilteredColimits.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/Slice.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/Structures.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/SliceFamEquiv.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/All.v
./runfile.sh UniMath/CategoryTheory/Profunctors/Core.v
./runfile.sh UniMath/CategoryTheory/categories/HSET/SetCoends.v
./runfile.sh UniMath/CategoryTheory/Profunctors/Examples.v
./runfile.sh UniMath/CategoryTheory/Profunctors/Transformation.v
./runfile.sh UniMath/CategoryTheory/Profunctors/Squares.v
./runfile.sh UniMath/CategoryTheory/SetValuedFunctors.v
./runfile.sh UniMath/CategoryTheory/categories/FinSet.v
./runfile.sh UniMath/CategoryTheory/categories/wosets.v
./runfile.sh UniMath/CategoryTheory/categories/Graph.v
./runfile.sh UniMath/CategoryTheory/categories/CGraph.v
./runfile.sh UniMath/CategoryTheory/GrothendieckTopos.v
./runfile.sh UniMath/CategoryTheory/Presheaf.v
./runfile.sh UniMath/CategoryTheory/ElementsOp.v
./runfile.sh UniMath/CategoryTheory/elems_slice_equiv.v
./runfile.sh UniMath/CategoryTheory/YonedaBinproducts.v
./runfile.sh UniMath/CategoryTheory/ExponentiationLeftAdjoint.v
./runfile.sh UniMath/CategoryTheory/Connected.v
./runfile.sh UniMath/CategoryTheory/LeftKanExtension.v
./runfile.sh UniMath/CategoryTheory/categories/CartesianCubicalSets.v
./runfile.sh UniMath/CategoryTheory/OppositeCategory/OppositeAdjunction.v
./runfile.sh UniMath/CategoryTheory/OppositeCategory/OppositeOfFunctorCategory.v
./runfile.sh UniMath/CategoryTheory/Chains/Chains.v
./runfile.sh UniMath/CategoryTheory/Chains/Cochains.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/DispFunctorPair.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/Opposite.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Fibrations.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/Reindexing.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Constructions.v
./runfile.sh UniMath/CategoryTheory/FunctorAlgebras.v
./runfile.sh UniMath/CategoryTheory/CompletelyIterativeAlgebras.v
./runfile.sh UniMath/CategoryTheory/Chains/Adamek.v
./runfile.sh UniMath/CategoryTheory/Chains/CoAdamek.v
./runfile.sh UniMath/CategoryTheory/Chains/OmegaCocontFunctors.v
./runfile.sh UniMath/CategoryTheory/OppositeCategory/LimitsAsColimits.v
./runfile.sh UniMath/CategoryTheory/Chains/OmegaContFunctors.v
./runfile.sh UniMath/CategoryTheory/Chains/All.v
./runfile.sh UniMath/CategoryTheory/Inductives/Lists.v
./runfile.sh UniMath/CategoryTheory/Inductives/Trees.v
./runfile.sh UniMath/CategoryTheory/Inductives/LambdaCalculus.v
./runfile.sh UniMath/CategoryTheory/Inductives/PropositionalLogic.v
./runfile.sh UniMath/CategoryTheory/CategoricalRecursionSchemes.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Equivalences.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/EquivalenceOverId.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/DisplayedCatEq.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Codomain.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Projection.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/SIP.v
./runfile.sh UniMath/CategoryTheory/Monads/Monads.v
./runfile.sh UniMath/CategoryTheory/Monads/LModules.v
./runfile.sh UniMath/CategoryTheory/Monads/Derivative.v
./runfile.sh UniMath/CategoryTheory/Monads/MonadAlgebras.v
./runfile.sh UniMath/CategoryTheory/Monads/Comonads.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Limits.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/Sigma.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/UnitalBinop.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/CategoryOfPosets.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Structures/CartesianStructure.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Structures/StructureLimitsAndColimits.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Structures/StructuresSmashProduct.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/AlgebraStructures.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/Cartesian.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/DCPOStructures.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/PointedDCPOStructures.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/PointedDCPOStrict.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/PointedPosetStrict.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/PointedPosetStructures.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/PointedSetStructures.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/PosetStructures.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Examples/SetStructures.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/FunctorCategory.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/Adjunctions.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/ComprehensionC.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/StreetFibration.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/StreetOpFibration.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/ReindexingForward.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/TotalCategoryFacts.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/TotalAdjunction.v
./runfile.sh UniMath/CategoryTheory/Monads/KleisliCategory.v
./runfile.sh UniMath/CategoryTheory/Monads/KTriples.v
./runfile.sh UniMath/CategoryTheory/Monads/Kleisli.v
./runfile.sh UniMath/CategoryTheory/Monads/KTriplesEquiv.v
./runfile.sh UniMath/CategoryTheory/limits/Examples/AlgebraStructuresColimits.v
./runfile.sh UniMath/CategoryTheory/categories/Dialgebras.v
./runfile.sh UniMath/CategoryTheory/categories/CatIsoInserter.v
./runfile.sh UniMath/CategoryTheory/categories/EilenbergMoore.v
./runfile.sh UniMath/CategoryTheory/categories/CoEilenbergMoore.v
./runfile.sh UniMath/CategoryTheory/categories/KleisliCategory.v
./runfile.sh UniMath/CategoryTheory/limits/Examples/EilenbergMooreLimits.v
./runfile.sh UniMath/CategoryTheory/Elements.v
./runfile.sh UniMath/CategoryTheory/Core.v
./runfile.sh UniMath/CategoryTheory/categories/Universal_Algebra/Algebras.v
./runfile.sh UniMath/CategoryTheory/categories/Universal_Algebra/EqAlgebras.v
./runfile.sh UniMath/CategoryTheory/categories/Relations.v
./runfile.sh UniMath/CategoryTheory/Monoidal/WhiskeredBifunctors.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Categories.v
./runfile.sh UniMath/CategoryTheory/Monoidal/StrongMonad.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Structure/Symmetric.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Structure/SymmetricDiagonal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Structure/Closed.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Structure/Cartesian.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Functors.v
./runfile.sh UniMath/CategoryTheory/Monoidal/FunctorCategories.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Adjunctions.v
./runfile.sh UniMath/CategoryTheory/Monoidal/CategoriesOfMonoids.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Displayed/WhiskeredDisplayedBifunctors.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Displayed/Monoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Displayed/TotalMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Displayed/MonoidalSections.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Displayed/TransportLemmas.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Displayed/Symmetric.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Displayed/SymmetricMonoidalBuilder.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/SetCartesianMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/CartesianMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/DisplayedCartesianMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/StructuresMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/EndofunctorsMonoidalElementary.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/MonadsAsMonoidsElementary.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/MonoidalPointedObjects.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Displayed/MonoidalFunctorLifting.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/MonoidalDialgebras.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/SymmetricMonoidalDialgebras.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/PointedSetCartesianMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/BinopCartesianMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/SetWithSubset.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/SmashProductMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/PosetsMonoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/Fullsub.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/Relations.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/Sigma.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/DiagonalFunctor.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/ConstantFunctor.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Comonoids/Category.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Comonoids/Tensor.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Comonoids/Monoidal.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Comonoids/Symmetric.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Comonoids/MonoidalCartesianBuilder.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Comonoids/CommComonoidsCartesian.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Comonoids/CartesianAsComonoids.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Comonoids/TransportComonoidAlongRetraction.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/LiftPoset.v
./runfile.sh UniMath/CategoryTheory/Monoidal/Examples/SymmetricMonoidalCoEilenbergMoore.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/MonoidalCategoriesReordered.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/MonoidalCategoriesTensored.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/EquivalenceWhiskeredNonCurriedMonoidalCategories.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/MonoidalCategoriesCurried.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/MonoidalFunctorsTensored.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/MonoidalFunctorsCurried.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/AugmentedSimplexCategory.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/DisplayedMonoidalTensored.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/DisplayedMonoidalCurried.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/CategoriesOfMonoids.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/BraidedMonoidalCategories.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/TotalDisplayedMonoidalCurried.v
./runfile.sh UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/MonoidalFunctorCategory.v
./runfile.sh UniMath/CategoryTheory/Actegories/Actegories.v
./runfile.sh UniMath/CategoryTheory/Actegories/ConstructionOfActegories.v
./runfile.sh UniMath/CategoryTheory/Actegories/MorphismsOfActegories.v
./runfile.sh UniMath/CategoryTheory/Actegories/ProductActegory.v
./runfile.sh UniMath/CategoryTheory/Actegories/ProductsInActegories.v
./runfile.sh UniMath/CategoryTheory/Actegories/CoproductsInActegories.v
./runfile.sh UniMath/CategoryTheory/Actegories/Examples/ActionOfEndomorphismsInCATElementary.v
./runfile.sh UniMath/CategoryTheory/Actegories/Examples/SelfActionInCATElementary.v
./runfile.sh UniMath/CategoryTheory/Actegories/ConstructionOfActegoryMorphisms.v
./runfile.sh UniMath/CategoryTheory/Actegories/ActionBasedStrongMonads.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/MoreFibrations/Prefibrations.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/MoreFibrations/CartesiannessOfComposites.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/MoreFibrations/FibrationsCharacterisation.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/MoreFibrations/DispCatsEquivFunctors.v
./runfile.sh UniMath/CategoryTheory/DisplayedCats/MoreFibrations/DisplayedDisplayedCats.v
./runfile.sh UniMath/CategoryTheory/SkewMonoidal/SkewMonoidalCategories.v
./runfile.sh UniMath/CategoryTheory/SkewMonoidal/CategoriesOfMonoids.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Enrichment.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/EnrichmentFunctor.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/EnrichmentTransformation.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/FullyFaithful.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/EnrichmentAdjunction.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/EnrichmentMonad.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Enriched/Enriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Enriched/ChangeOfBase.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Enriched/Opposite.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Enriched/UnderlyingCategory.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Enriched/EnrichmentEquiv.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/SelfEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedTerminal.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedBinaryProducts.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedProducts.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedEqualizers.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedConicalLimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedPowers.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/EnrichedLimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedInitial.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedBinaryCoproducts.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedCoproducts.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedCoequalizers.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedConicalColimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedCopowers.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/EnrichedColimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/CopowerFunctor.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/SetEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/PosetEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/StructureEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/SmashStructureEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/HomFunctor.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/OppositeEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/FunctorCategory.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/Precomposition.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/Presheaves.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/Yoneda.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/YonedaLemma.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/EmptyEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/UnitEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/FullSubEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/ImageEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/DialgebraEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/SliceEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/EilenbergMooreEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/ProductEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/ChangeOfBase.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/RezkCompletion/PrecompFullyFaithful.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/RezkCompletion/PrecompEssentiallySurjective.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/RezkCompletion/EnrichedRezkCompletion.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/RezkCompletion/RezkUniversalProperty.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/KleisliEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/UnivalentKleisliEnriched.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Examples/UnivalentKleisliMapping.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/Examples/OppositeEnrichedLimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/Examples/PosetEnrichedLimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/Examples/StructureEnrichedLimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Limits/Examples/SelfEnrichedLimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/Examples/OppositeEnrichedColimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/Examples/PosetEnrichedColimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/Examples/StructureEnrichedColimits.v
./runfile.sh UniMath/CategoryTheory/EnrichedCats/Colimits/Examples/SelfEnrichedColimits.v
./runfile.sh UniMath/CategoryTheory/GrothendieckConstruction/TotalCategory.v
./runfile.sh UniMath/CategoryTheory/GrothendieckConstruction/IsosInTotal.v
./runfile.sh UniMath/CategoryTheory/GrothendieckConstruction/Projection.v
./runfile.sh UniMath/CategoryTheory/GrothendieckConstruction/IsOpfibration.v
./runfile.sh UniMath/CategoryTheory/GrothendieckConstruction/IsPullback.v
