(** File generated by coq-of-ocaml *)
Require Import CoqOfOCaml.CoqOfOCaml.
Require Import CoqOfOCaml.Settings.

Definition string_list (x : Set) : Set := list x.

Inductive ast_desc : Set :=
| Adxu : ast_desc
| Ad_Ad_arg_label_expression_list_Da : ast_desc
| Ad_Ad_attributes_Da : ast_desc
| Ad_Ad_bool_Da : ast_desc
| Ad_Ad_empty_list_Da : ast_desc
| Ad_Ad_int_Da : ast_desc
| Ad_Ad_list : ast_desc
| Ad_Ad_loc2_Da : ast_desc
| Ad_Ad_loc_Da : ast_desc
| Ad_Ad_loc_stack_Da : ast_desc
| Ad_Ad_pos_Da : ast_desc
| Ad_Ad_process_arg_constructor_declaration_Da : ast_desc
| Ad_Ad_process_arg_label_expression_Da : ast_desc
| Ad_Ad_process_arg_label_expression_list_Da : ast_desc
| Ad_Ad_process_ast_desc : ast_desc
| Ad_Ad_process_cases : ast_desc
| Ad_Ad_process_cstrs_Da : ast_desc
| Ad_Ad_process_generic_list_Da : ast_desc
| Ad_Ad_process_label_declaration_list_Da : ast_desc
| Ad_Ad_process_list_tail_Da : ast_desc
| Ad_Ad_process_loc_Da : ast_desc
| Ad_Ad_process_params_Da : ast_desc
| Ad_Ad_process_string_loc_list_pattern_option_Da : ast_desc
| Ad_Ad_process_structure_item_Da : ast_desc
| Ad_Ad_process_structure_item_desc_Da : ast_desc
| Ad_Ad_process_structure_items_Da : ast_desc
| Ad_Ad_process_type_declaration_list_Da : ast_desc
| Ad_Ad_process_value_binding_list_Da : ast_desc
| Ad_Ad_process_var_list_Da : ast_desc
| Ad_Ad_quote_Da : ast_desc
| Ad_Definition : ast_desc
| Ad_FIXME : ast_desc
| Ad_FIXME_process_ast_desc : ast_desc
| Ad_Fixme1 : ast_desc
| Ad_Fixme2_Da : ast_desc
| Ad_Ident : ast_desc -> ast_desc
| Ad_MetaCoq_Definition : ast_desc
| Ad_NEW : ast_desc
| Ad_NoString : ast_desc
| Ad_Nolabel_Da : ast_desc
| Ad_None : ast_desc
| Ad_Nonrecursive_Da : ast_desc
| Ad_Obj : ast_desc
| Ad_P4 : ast_desc
| Ad_Pconst_string_Da : ast_desc
| Ad_Pexp_apply_Da : ast_desc
| Ad_Pexp_constant_Da : ast_desc
| Ad_Pexp_constraint_Da : ast_desc
| Ad_Pexp_construct_Da : ast_desc
| Ad_Pexp_fun_Da : ast_desc
| Ad_Pexp_ident_Da : ast_desc
| Ad_Pexp_tuple_Da : ast_desc
| Ad_Ppat_constraint_Da : ast_desc
| Ad_Ppat_var_Da : ast_desc
| Ad_Pstr_type_Da : ast_desc
| Ad_Pstr_value_Da : ast_desc
| Ad_Ptyp_constr_Da : ast_desc
| Ad_Ptype_abstract_Da : ast_desc
| Ad_Public_Da : ast_desc
| Ad_Recursive_Da : ast_desc
| Ad_String : ast_desc -> ast_desc
| Ad_TRUNCATED : ast_desc
| Ad_TypeParam_T : ast_desc
| Ad_TypeParam_T_dot : ast_desc
| Ad_Type_UUU : ast_desc
| Ad_Da_Da : ast_desc
| Ad_Da_Da_Da : ast_desc
| Ad_ : ast_desc
| Ad_Da : ast_desc
| Ad_a_Da : ast_desc
| Ad_arg_label_Da : ast_desc
| Ad_arg_label_expression_list : ast_desc -> ast_desc
| Ad_ast_desc : ast_desc
| Ad_ast_desc_Da : ast_desc
| Ad_attributes : ast_desc
| Ad_b_Da : ast_desc
| Ad_bool : ast_desc -> ast_desc
| Ad_c_Da : ast_desc
| Ad_caret : ast_desc
| Ad_close_parens : ast_desc
| Ad_close_parens_Da_Da : ast_desc
| Ad_closebrace : ast_desc
| Ad_constant_Da : ast_desc
| Ad_core_type_desc_Da : ast_desc
| Ad_empty : ast_desc
| Ad_empty_array : ast_desc
| Ad_error : ast_desc
| Ad_errr : ast_desc
| Ad_expression_desc_Da : ast_desc
| Ad_fixme : ast_desc -> ast_desc
| Ad_foo1_Da : ast_desc
| Ad_ident_Da : ast_desc
| Ad_int : ast_desc -> ast_desc
| Ad_list : ast_desc -> ast_desc
| Ad_list_Da : ast_desc
| Ad_loc : ast_desc
| Ad_loc2 : ast_desc
| Ad_loc2_Da : ast_desc
| Ad_loc_Da : ast_desc
| Ad_loc_stack : ast_desc
| Ad_loc_stack_Da : ast_desc
| Ad_none_Da : ast_desc
| Ad_open_parenAd_Ident : ast_desc
| Ad_open_parenAd_String : ast_desc
| Ad_open_paren_rec_root : ast_desc
| Ad_openbrace : ast_desc
| Ad_pattern_desc_Da : ast_desc
| Ad_pos : ast_desc
| Ad_private_flag_Da : ast_desc
| Ad_process_arg_constructor_declaration : ast_desc -> ast_desc
| Ad_process_arg_constructor_declaration_Da : ast_desc
| Ad_process_arg_label_expression : ast_desc -> ast_desc -> ast_desc
| Ad_process_arg_label_expression_Da : ast_desc
| Ad_process_arg_label_expression_list : ast_desc -> ast_desc
| Ad_process_ast_desc : ast_desc -> ast_desc
| Ad_process_ast_desc_loc_list_pattern_option : ast_desc
| Ad_process_cases : ast_desc -> ast_desc
| Ad_process_core_type_list_Da : ast_desc
| Ad_process_cstrs : ast_desc -> ast_desc
| Ad_process_cstrs_Da : ast_desc
| Ad_process_expression_list_Da : ast_desc
| Ad_process_generic_list : ast_desc -> ast_desc -> ast_desc
| Ad_process_generic_type : ast_desc
| Ad_process_generic_type3 : ast_desc
| Ad_process_generic_type_Da : ast_desc
| Ad_process_label_declaration_list : ast_desc -> ast_desc
| Ad_process_label_declaration_list_Da : ast_desc
| Ad_process_list_tail : ast_desc -> ast_desc -> ast_desc
| Ad_process_loc : ast_desc -> ast_desc
| Ad_process_loc_Da : ast_desc
| Ad_process_params : ast_desc -> ast_desc
| Ad_process_params_Da : ast_desc
| Ad_process_string : ast_desc
| Ad_process_string_loc_list_pattern_option : ast_desc
| Ad_process_string_loc_list_pattern_option_Da : ast_desc
| Ad_process_structure_item : ast_desc -> ast_desc
| Ad_process_structure_item_desc : ast_desc -> ast_desc
| Ad_process_structure_items : ast_desc -> ast_desc
| Ad_process_structure_items_Da : ast_desc
| Ad_process_type_declaration_list : ast_desc -> ast_desc
| Ad_process_type_declaration_list_Da : ast_desc
| Ad_process_value_binding_list : ast_desc
| Ad_process_var_list : ast_desc -> ast_desc
| Ad_process_vars_list_Da : ast_desc
| Ad_quot_list : ast_desc -> ast_desc
| Ad_quote : ast_desc -> ast_desc -> ast_desc
| Ad_rec_flag_Da : ast_desc
| Ad_root : ast_desc -> ast_desc
| Ad_string_Da : ast_desc
| Ad_structure_item_desc_Da : ast_desc
| Ad_todofixme : ast_desc
| Ad_type_kind_Da : ast_desc
| Ad_umcr_n_role_ : ast_desc
| Ad_umcr_n_type_ : ast_desc
| Ad_umcr_r_rel_ : ast_desc
| Ad_umcr_type : ast_desc
| Ad_x_Da : ast_desc
| Ad_y_Da : ast_desc
| Coq_ad_nostring : ast_desc.

Fixpoint ast_desc_rect {A : Set}
  (f_value : A) (f0 : A) (f1 : A) (f2 : A) (f3 : A) (f4 : A) (f5 : A) (f6 : A)
  (f7 : A) (f8 : A) (f9 : A) (f10 : A) (f11 : A) (f12 : A) (f13 : A) (f14 : A)
  (f15 : A) (f16 : A) (f17 : A) (f18 : A) (f19 : A) (f20 : A) (f21 : A)
  (f22 : A) (f23 : A) (f24 : A) (f25 : A) (f26 : A) (f27 : A) (f28 : A)
  (f29 : A) (f30 : A) (f31 : A) (f32 : A) (f33 : A) (f34 : ast_desc -> A -> A)
  (f35 : A) (f36 : A) (f37 : A) (f38 : A) (f39 : A) (f40 : A) (f41 : A)
  (f42 : A) (f43 : A) (f44 : A) (f45 : A) (f46 : A) (f47 : A) (f48 : A)
  (f49 : A) (f50 : A) (f51 : A) (f52 : A) (f53 : A) (f54 : A) (f55 : A)
  (f56 : A) (f57 : A) (f58 : A) (f59 : ast_desc -> A -> A) (f60 : A) (f61 : A)
  (f62 : A) (f63 : A) (f64 : A) (f65 : A) (f66 : A) (f67 : A) (f68 : A)
  (f69 : A) (f70 : ast_desc -> A -> A) (f71 : A) (f72 : A) (f73 : A) (f74 : A)
  (f75 : ast_desc -> A -> A) (f76 : A) (f77 : A) (f78 : A) (f79 : A) (f80 : A)
  (f81 : A) (f82 : A) (f83 : A) (f84 : A) (f85 : A) (f86 : A) (f87 : A)
  (f88 : ast_desc -> A -> A) (f89 : A) (f90 : A) (f91 : ast_desc -> A -> A)
  (f92 : ast_desc -> A -> A) (f93 : A) (f94 : A) (f95 : A) (f96 : A) (f97 : A)
  (f98 : A) (f99 : A) (f100 : A) (f101 : A) (f102 : A) (f103 : A) (f104 : A)
  (f105 : A) (f106 : A) (f107 : A) (f108 : ast_desc -> A -> A) (f109 : A)
  (f110 : ast_desc -> A -> ast_desc -> A -> A) (f111 : A)
  (f112 : ast_desc -> A -> A) (f113 : ast_desc -> A -> A) (f114 : A)
  (f115 : ast_desc -> A -> A) (f116 : A) (f117 : ast_desc -> A -> A) (f118 : A)
  (f119 : A) (f120 : ast_desc -> A -> ast_desc -> A -> A) (f121 : A) (f122 : A)
  (f123 : A) (f124 : ast_desc -> A -> A) (f125 : A)
  (f126 : ast_desc -> A -> ast_desc -> A -> A) (f127 : ast_desc -> A -> A)
  (f128 : A) (f129 : ast_desc -> A -> A) (f130 : A) (f131 : A) (f132 : A)
  (f133 : A) (f134 : ast_desc -> A -> A) (f135 : ast_desc -> A -> A)
  (f136 : ast_desc -> A -> A) (f137 : A) (f138 : ast_desc -> A -> A) (f139 : A)
  (f140 : A) (f141 : ast_desc -> A -> A) (f142 : A) (f143 : ast_desc -> A -> A)
  (f144 : ast_desc -> A -> ast_desc -> A -> A) (f145 : A)
  (f146 : ast_desc -> A -> A) (f147 : A) (f148 : A) (f149 : A) (f150 : A)
  (f151 : A) (f152 : A) (f153 : A) (f154 : A) (f155 : A) (f156 : A) (f157 : A)
  (function_parameter : ast_desc) : A :=
  match function_parameter with
  | Adxu => f_value
  | Ad_Ad_arg_label_expression_list_Da => f0
  | Ad_Ad_attributes_Da => f1
  | Ad_Ad_bool_Da => f2
  | Ad_Ad_empty_list_Da => f3
  | Ad_Ad_int_Da => f4
  | Ad_Ad_list => f5
  | Ad_Ad_loc2_Da => f6
  | Ad_Ad_loc_Da => f7
  | Ad_Ad_loc_stack_Da => f8
  | Ad_Ad_pos_Da => f9
  | Ad_Ad_process_arg_constructor_declaration_Da => f10
  | Ad_Ad_process_arg_label_expression_Da => f11
  | Ad_Ad_process_arg_label_expression_list_Da => f12
  | Ad_Ad_process_ast_desc => f13
  | Ad_Ad_process_cases => f14
  | Ad_Ad_process_cstrs_Da => f15
  | Ad_Ad_process_generic_list_Da => f16
  | Ad_Ad_process_label_declaration_list_Da => f17
  | Ad_Ad_process_list_tail_Da => f18
  | Ad_Ad_process_loc_Da => f19
  | Ad_Ad_process_params_Da => f20
  | Ad_Ad_process_string_loc_list_pattern_option_Da => f21
  | Ad_Ad_process_structure_item_Da => f22
  | Ad_Ad_process_structure_item_desc_Da => f23
  | Ad_Ad_process_structure_items_Da => f24
  | Ad_Ad_process_type_declaration_list_Da => f25
  | Ad_Ad_process_value_binding_list_Da => f26
  | Ad_Ad_process_var_list_Da => f27
  | Ad_Ad_quote_Da => f28
  | Ad_Definition => f29
  | Ad_FIXME => f30
  | Ad_FIXME_process_ast_desc => f31
  | Ad_Fixme1 => f32
  | Ad_Fixme2_Da => f33
  | Ad_Ident a0 =>
    f34 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_MetaCoq_Definition => f35
  | Ad_NEW => f36
  | Ad_NoString => f37
  | Ad_Nolabel_Da => f38
  | Ad_None => f39
  | Ad_Nonrecursive_Da => f40
  | Ad_Obj => f41
  | Ad_P4 => f42
  | Ad_Pconst_string_Da => f43
  | Ad_Pexp_apply_Da => f44
  | Ad_Pexp_constant_Da => f45
  | Ad_Pexp_constraint_Da => f46
  | Ad_Pexp_construct_Da => f47
  | Ad_Pexp_fun_Da => f48
  | Ad_Pexp_ident_Da => f49
  | Ad_Pexp_tuple_Da => f50
  | Ad_Ppat_constraint_Da => f51
  | Ad_Ppat_var_Da => f52
  | Ad_Pstr_type_Da => f53
  | Ad_Pstr_value_Da => f54
  | Ad_Ptyp_constr_Da => f55
  | Ad_Ptype_abstract_Da => f56
  | Ad_Public_Da => f57
  | Ad_Recursive_Da => f58
  | Ad_String a0 =>
    f59 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_TRUNCATED => f60
  | Ad_TypeParam_T => f61
  | Ad_TypeParam_T_dot => f62
  | Ad_Type_UUU => f63
  | Ad_Da_Da => f64
  | Ad_Da_Da_Da => f65
  | Ad_ => f66
  | Ad_Da => f67
  | Ad_a_Da => f68
  | Ad_arg_label_Da => f69
  | Ad_arg_label_expression_list a0 =>
    f70 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_ast_desc => f71
  | Ad_ast_desc_Da => f72
  | Ad_attributes => f73
  | Ad_b_Da => f74
  | Ad_bool a0 =>
    f75 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_c_Da => f76
  | Ad_caret => f77
  | Ad_close_parens => f78
  | Ad_close_parens_Da_Da => f79
  | Ad_closebrace => f80
  | Ad_constant_Da => f81
  | Ad_core_type_desc_Da => f82
  | Ad_empty => f83
  | Ad_empty_array => f84
  | Ad_error => f85
  | Ad_errr => f86
  | Ad_expression_desc_Da => f87
  | Ad_fixme a0 =>
    f88 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_foo1_Da => f89
  | Ad_ident_Da => f90
  | Ad_int a0 =>
    f91 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_list a0 =>
    f92 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_list_Da => f93
  | Ad_loc => f94
  | Ad_loc2 => f95
  | Ad_loc2_Da => f96
  | Ad_loc_Da => f97
  | Ad_loc_stack => f98
  | Ad_loc_stack_Da => f99
  | Ad_none_Da => f100
  | Ad_open_parenAd_Ident => f101
  | Ad_open_parenAd_String => f102
  | Ad_open_paren_rec_root => f103
  | Ad_openbrace => f104
  | Ad_pattern_desc_Da => f105
  | Ad_pos => f106
  | Ad_private_flag_Da => f107
  | Ad_process_arg_constructor_declaration a0 =>
    f108 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_arg_constructor_declaration_Da => f109
  | Ad_process_arg_label_expression a0 a1 =>
    f110 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0) a1
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a1)
  | Ad_process_arg_label_expression_Da => f111
  | Ad_process_arg_label_expression_list a0 =>
    f112 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_ast_desc a0 =>
    f113 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_ast_desc_loc_list_pattern_option => f114
  | Ad_process_cases a0 =>
    f115 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_core_type_list_Da => f116
  | Ad_process_cstrs a0 =>
    f117 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_cstrs_Da => f118
  | Ad_process_expression_list_Da => f119
  | Ad_process_generic_list a0 a1 =>
    f120 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0) a1
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a1)
  | Ad_process_generic_type => f121
  | Ad_process_generic_type3 => f122
  | Ad_process_generic_type_Da => f123
  | Ad_process_label_declaration_list a0 =>
    f124 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_label_declaration_list_Da => f125
  | Ad_process_list_tail a0 a1 =>
    f126 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0) a1
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a1)
  | Ad_process_loc a0 =>
    f127 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_loc_Da => f128
  | Ad_process_params a0 =>
    f129 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_params_Da => f130
  | Ad_process_string => f131
  | Ad_process_string_loc_list_pattern_option => f132
  | Ad_process_string_loc_list_pattern_option_Da => f133
  | Ad_process_structure_item a0 =>
    f134 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_structure_item_desc a0 =>
    f135 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_structure_items a0 =>
    f136 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_structure_items_Da => f137
  | Ad_process_type_declaration_list a0 =>
    f138 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_type_declaration_list_Da => f139
  | Ad_process_value_binding_list => f140
  | Ad_process_var_list a0 =>
    f141 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_vars_list_Da => f142
  | Ad_quot_list a0 =>
    f143 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_quote a0 a1 =>
    f144 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0) a1
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a1)
  | Ad_rec_flag_Da => f145
  | Ad_root a0 =>
    f146 a0
      (ast_desc_rect f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_string_Da => f147
  | Ad_structure_item_desc_Da => f148
  | Ad_todofixme => f149
  | Ad_type_kind_Da => f150
  | Ad_umcr_n_role_ => f151
  | Ad_umcr_n_type_ => f152
  | Ad_umcr_r_rel_ => f153
  | Ad_umcr_type => f154
  | Ad_x_Da => f155
  | Ad_y_Da => f156
  | Coq_ad_nostring => f157
  end.

Fixpoint ast_desc_rec {A : Set}
  (f_value : A) (f0 : A) (f1 : A) (f2 : A) (f3 : A) (f4 : A) (f5 : A) (f6 : A)
  (f7 : A) (f8 : A) (f9 : A) (f10 : A) (f11 : A) (f12 : A) (f13 : A) (f14 : A)
  (f15 : A) (f16 : A) (f17 : A) (f18 : A) (f19 : A) (f20 : A) (f21 : A)
  (f22 : A) (f23 : A) (f24 : A) (f25 : A) (f26 : A) (f27 : A) (f28 : A)
  (f29 : A) (f30 : A) (f31 : A) (f32 : A) (f33 : A) (f34 : ast_desc -> A -> A)
  (f35 : A) (f36 : A) (f37 : A) (f38 : A) (f39 : A) (f40 : A) (f41 : A)
  (f42 : A) (f43 : A) (f44 : A) (f45 : A) (f46 : A) (f47 : A) (f48 : A)
  (f49 : A) (f50 : A) (f51 : A) (f52 : A) (f53 : A) (f54 : A) (f55 : A)
  (f56 : A) (f57 : A) (f58 : A) (f59 : ast_desc -> A -> A) (f60 : A) (f61 : A)
  (f62 : A) (f63 : A) (f64 : A) (f65 : A) (f66 : A) (f67 : A) (f68 : A)
  (f69 : A) (f70 : ast_desc -> A -> A) (f71 : A) (f72 : A) (f73 : A) (f74 : A)
  (f75 : ast_desc -> A -> A) (f76 : A) (f77 : A) (f78 : A) (f79 : A) (f80 : A)
  (f81 : A) (f82 : A) (f83 : A) (f84 : A) (f85 : A) (f86 : A) (f87 : A)
  (f88 : ast_desc -> A -> A) (f89 : A) (f90 : A) (f91 : ast_desc -> A -> A)
  (f92 : ast_desc -> A -> A) (f93 : A) (f94 : A) (f95 : A) (f96 : A) (f97 : A)
  (f98 : A) (f99 : A) (f100 : A) (f101 : A) (f102 : A) (f103 : A) (f104 : A)
  (f105 : A) (f106 : A) (f107 : A) (f108 : ast_desc -> A -> A) (f109 : A)
  (f110 : ast_desc -> A -> ast_desc -> A -> A) (f111 : A)
  (f112 : ast_desc -> A -> A) (f113 : ast_desc -> A -> A) (f114 : A)
  (f115 : ast_desc -> A -> A) (f116 : A) (f117 : ast_desc -> A -> A) (f118 : A)
  (f119 : A) (f120 : ast_desc -> A -> ast_desc -> A -> A) (f121 : A) (f122 : A)
  (f123 : A) (f124 : ast_desc -> A -> A) (f125 : A)
  (f126 : ast_desc -> A -> ast_desc -> A -> A) (f127 : ast_desc -> A -> A)
  (f128 : A) (f129 : ast_desc -> A -> A) (f130 : A) (f131 : A) (f132 : A)
  (f133 : A) (f134 : ast_desc -> A -> A) (f135 : ast_desc -> A -> A)
  (f136 : ast_desc -> A -> A) (f137 : A) (f138 : ast_desc -> A -> A) (f139 : A)
  (f140 : A) (f141 : ast_desc -> A -> A) (f142 : A) (f143 : ast_desc -> A -> A)
  (f144 : ast_desc -> A -> ast_desc -> A -> A) (f145 : A)
  (f146 : ast_desc -> A -> A) (f147 : A) (f148 : A) (f149 : A) (f150 : A)
  (f151 : A) (f152 : A) (f153 : A) (f154 : A) (f155 : A) (f156 : A) (f157 : A)
  (function_parameter : ast_desc) : A :=
  match function_parameter with
  | Adxu => f_value
  | Ad_Ad_arg_label_expression_list_Da => f0
  | Ad_Ad_attributes_Da => f1
  | Ad_Ad_bool_Da => f2
  | Ad_Ad_empty_list_Da => f3
  | Ad_Ad_int_Da => f4
  | Ad_Ad_list => f5
  | Ad_Ad_loc2_Da => f6
  | Ad_Ad_loc_Da => f7
  | Ad_Ad_loc_stack_Da => f8
  | Ad_Ad_pos_Da => f9
  | Ad_Ad_process_arg_constructor_declaration_Da => f10
  | Ad_Ad_process_arg_label_expression_Da => f11
  | Ad_Ad_process_arg_label_expression_list_Da => f12
  | Ad_Ad_process_ast_desc => f13
  | Ad_Ad_process_cases => f14
  | Ad_Ad_process_cstrs_Da => f15
  | Ad_Ad_process_generic_list_Da => f16
  | Ad_Ad_process_label_declaration_list_Da => f17
  | Ad_Ad_process_list_tail_Da => f18
  | Ad_Ad_process_loc_Da => f19
  | Ad_Ad_process_params_Da => f20
  | Ad_Ad_process_string_loc_list_pattern_option_Da => f21
  | Ad_Ad_process_structure_item_Da => f22
  | Ad_Ad_process_structure_item_desc_Da => f23
  | Ad_Ad_process_structure_items_Da => f24
  | Ad_Ad_process_type_declaration_list_Da => f25
  | Ad_Ad_process_value_binding_list_Da => f26
  | Ad_Ad_process_var_list_Da => f27
  | Ad_Ad_quote_Da => f28
  | Ad_Definition => f29
  | Ad_FIXME => f30
  | Ad_FIXME_process_ast_desc => f31
  | Ad_Fixme1 => f32
  | Ad_Fixme2_Da => f33
  | Ad_Ident a0 =>
    f34 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_MetaCoq_Definition => f35
  | Ad_NEW => f36
  | Ad_NoString => f37
  | Ad_Nolabel_Da => f38
  | Ad_None => f39
  | Ad_Nonrecursive_Da => f40
  | Ad_Obj => f41
  | Ad_P4 => f42
  | Ad_Pconst_string_Da => f43
  | Ad_Pexp_apply_Da => f44
  | Ad_Pexp_constant_Da => f45
  | Ad_Pexp_constraint_Da => f46
  | Ad_Pexp_construct_Da => f47
  | Ad_Pexp_fun_Da => f48
  | Ad_Pexp_ident_Da => f49
  | Ad_Pexp_tuple_Da => f50
  | Ad_Ppat_constraint_Da => f51
  | Ad_Ppat_var_Da => f52
  | Ad_Pstr_type_Da => f53
  | Ad_Pstr_value_Da => f54
  | Ad_Ptyp_constr_Da => f55
  | Ad_Ptype_abstract_Da => f56
  | Ad_Public_Da => f57
  | Ad_Recursive_Da => f58
  | Ad_String a0 =>
    f59 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_TRUNCATED => f60
  | Ad_TypeParam_T => f61
  | Ad_TypeParam_T_dot => f62
  | Ad_Type_UUU => f63
  | Ad_Da_Da => f64
  | Ad_Da_Da_Da => f65
  | Ad_ => f66
  | Ad_Da => f67
  | Ad_a_Da => f68
  | Ad_arg_label_Da => f69
  | Ad_arg_label_expression_list a0 =>
    f70 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_ast_desc => f71
  | Ad_ast_desc_Da => f72
  | Ad_attributes => f73
  | Ad_b_Da => f74
  | Ad_bool a0 =>
    f75 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_c_Da => f76
  | Ad_caret => f77
  | Ad_close_parens => f78
  | Ad_close_parens_Da_Da => f79
  | Ad_closebrace => f80
  | Ad_constant_Da => f81
  | Ad_core_type_desc_Da => f82
  | Ad_empty => f83
  | Ad_empty_array => f84
  | Ad_error => f85
  | Ad_errr => f86
  | Ad_expression_desc_Da => f87
  | Ad_fixme a0 =>
    f88 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_foo1_Da => f89
  | Ad_ident_Da => f90
  | Ad_int a0 =>
    f91 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_list a0 =>
    f92 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_list_Da => f93
  | Ad_loc => f94
  | Ad_loc2 => f95
  | Ad_loc2_Da => f96
  | Ad_loc_Da => f97
  | Ad_loc_stack => f98
  | Ad_loc_stack_Da => f99
  | Ad_none_Da => f100
  | Ad_open_parenAd_Ident => f101
  | Ad_open_parenAd_String => f102
  | Ad_open_paren_rec_root => f103
  | Ad_openbrace => f104
  | Ad_pattern_desc_Da => f105
  | Ad_pos => f106
  | Ad_private_flag_Da => f107
  | Ad_process_arg_constructor_declaration a0 =>
    f108 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_arg_constructor_declaration_Da => f109
  | Ad_process_arg_label_expression a0 a1 =>
    f110 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0) a1
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a1)
  | Ad_process_arg_label_expression_Da => f111
  | Ad_process_arg_label_expression_list a0 =>
    f112 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_ast_desc a0 =>
    f113 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_ast_desc_loc_list_pattern_option => f114
  | Ad_process_cases a0 =>
    f115 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_core_type_list_Da => f116
  | Ad_process_cstrs a0 =>
    f117 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_cstrs_Da => f118
  | Ad_process_expression_list_Da => f119
  | Ad_process_generic_list a0 a1 =>
    f120 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0) a1
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a1)
  | Ad_process_generic_type => f121
  | Ad_process_generic_type3 => f122
  | Ad_process_generic_type_Da => f123
  | Ad_process_label_declaration_list a0 =>
    f124 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_label_declaration_list_Da => f125
  | Ad_process_list_tail a0 a1 =>
    f126 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0) a1
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a1)
  | Ad_process_loc a0 =>
    f127 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_loc_Da => f128
  | Ad_process_params a0 =>
    f129 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_params_Da => f130
  | Ad_process_string => f131
  | Ad_process_string_loc_list_pattern_option => f132
  | Ad_process_string_loc_list_pattern_option_Da => f133
  | Ad_process_structure_item a0 =>
    f134 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_structure_item_desc a0 =>
    f135 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_structure_items a0 =>
    f136 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_structure_items_Da => f137
  | Ad_process_type_declaration_list a0 =>
    f138 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_type_declaration_list_Da => f139
  | Ad_process_value_binding_list => f140
  | Ad_process_var_list a0 =>
    f141 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_process_vars_list_Da => f142
  | Ad_quot_list a0 =>
    f143 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_quote a0 a1 =>
    f144 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0) a1
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a1)
  | Ad_rec_flag_Da => f145
  | Ad_root a0 =>
    f146 a0
      (ast_desc_rec f_value f0 f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14
        f15 f16 f17 f18 f19 f20 f21 f22 f23 f24 f25 f26 f27 f28 f29 f30 f31 f32
        f33 f34 f35 f36 f37 f38 f39 f40 f41 f42 f43 f44 f45 f46 f47 f48 f49 f50
        f51 f52 f53 f54 f55 f56 f57 f58 f59 f60 f61 f62 f63 f64 f65 f66 f67 f68
        f69 f70 f71 f72 f73 f74 f75 f76 f77 f78 f79 f80 f81 f82 f83 f84 f85 f86
        f87 f88 f89 f90 f91 f92 f93 f94 f95 f96 f97 f98 f99 f100 f101 f102 f103
        f104 f105 f106 f107 f108 f109 f110 f111 f112 f113 f114 f115 f116 f117
        f118 f119 f120 f121 f122 f123 f124 f125 f126 f127 f128 f129 f130 f131
        f132 f133 f134 f135 f136 f137 f138 f139 f140 f141 f142 f143 f144 f145
        f146 f147 f148 f149 f150 f151 f152 f153 f154 f155 f156 f157 a0)
  | Ad_string_Da => f147
  | Ad_structure_item_desc_Da => f148
  | Ad_todofixme => f149
  | Ad_type_kind_Da => f150
  | Ad_umcr_n_role_ => f151
  | Ad_umcr_n_type_ => f152
  | Ad_umcr_r_rel_ => f153
  | Ad_umcr_type => f154
  | Ad_x_Da => f155
  | Ad_y_Da => f156
  | Coq_ad_nostring => f157
  end.

Inductive ast_desc_list : Set :=
| Ad_empty_list : ast_desc_list
| Ad_cons : ast_desc -> ast_desc_list -> ast_desc_list.

Fixpoint ast_desc_list_rect {A : Set}
  (f_value : A) (f0 : ast_desc -> ast_desc_list -> A -> A)
  (function_parameter : ast_desc_list) : A :=
  match function_parameter with
  | Ad_empty_list => f_value
  | Ad_cons a0 a1 => f0 a0 a1 (ast_desc_list_rect f_value f0 a1)
  end.

Fixpoint ast_desc_list_rec {A : Set}
  (f_value : A) (f0 : ast_desc -> ast_desc_list -> A -> A)
  (function_parameter : ast_desc_list) : A :=
  match function_parameter with
  | Ad_empty_list => f_value
  | Ad_cons a0 a1 => f0 a0 a1 (ast_desc_list_rec f_value f0 a1)
  end.

Definition ident (a_value : ast_desc) : ast_desc := Ad_Ident a_value.

Definition none : ast_desc := Ad_None.

Definition process_cases (x_value : ast_desc) : ast_desc :=
  Ad_process_cases x_value.

Definition process_var_list (x_value : ast_desc) : ast_desc :=
  Ad_process_var_list x_value.

Definition process_arg_constructor_declaration (x_value : ast_desc)
  : ast_desc := Ad_process_arg_constructor_declaration x_value.

Definition process_label_declaration_list (x_value : ast_desc) : ast_desc :=
  Ad_process_label_declaration_list x_value.

Definition process_params (x_value : ast_desc) : ast_desc :=
  Ad_process_params x_value.

Definition process_cstrs (x_value : ast_desc) : ast_desc :=
  Ad_process_cstrs x_value.

Definition process_type_declaration_list (x_value : ast_desc) : ast_desc :=
  Ad_process_type_declaration_list x_value.

Definition loc : ast_desc := Ad_loc.

Definition loc2 : ast_desc := Ad_loc2.

Definition loc_stack : ast_desc := Ad_loc_stack.

Definition process_loc (a_value : ast_desc) : ast_desc :=
  Ad_process_loc a_value.

Definition process_string_loc_list_pattern_option : ast_desc :=
  Ad_process_string_loc_list_pattern_option.

Definition process_arg_label_expression
  (x_value : ast_desc) (y_value : ast_desc) : ast_desc :=
  Ad_process_arg_label_expression x_value y_value.

Definition process_expression_list (x_value : ast_desc) : ast_desc :=
  Ad_arg_label_expression_list x_value.

Definition process_arg_label_expression_list (a_value : ast_desc) : ast_desc :=
  Ad_process_arg_label_expression_list a_value.

Definition process_location (a_value : ast_desc) : ast_desc :=
  Ad_process_loc a_value.

Definition process_location_stack (a_value : ast_desc) : ast_desc :=
  Ad_process_loc a_value.

Definition attributes : ast_desc := Ad_attributes.

Definition process_value_binding_list : ast_desc :=
  Ad_process_value_binding_list.

Definition pos (a_value : ast_desc) : ast_desc := Ad_process_loc a_value.

Definition b_value (a_value : ast_desc) : ast_desc := Ad_bool a_value.

Definition mint (a_value : ast_desc) : ast_desc := Ad_int a_value.

Definition string_value (a_value : ast_desc) : ast_desc := Ad_String a_value.

Definition make_pair {A B : Set} (function_parameter : A) : B -> ast_desc :=
  let '_ := function_parameter in
  fun (function_parameter : B) =>
    let '_ := function_parameter in
    Ad_None.

Definition process_string_option : ast_desc := Ad_NoString.

Definition process_structure_items (x_value : ast_desc) : ast_desc :=
  Ad_process_structure_items x_value.

Definition my_append {A B : Set} (a_value : A) (function_parameter : B) : A :=
  let '_ := function_parameter in
  a_value.

Definition process_generic_type3 {A B C : Set}
  (a_value : A) (b_value0 : B) (function_parameter : C) : ast_desc :=
  let '_ := function_parameter in
  my_append Ad_process_generic_type3
    (my_append a_value
      (my_append Ad_caret
        (my_append b_value0
          (my_append Ad_openbrace (my_append Ad_None Ad_closebrace))))).

Definition quot (a_value : ast_desc) (b_value0 : ast_desc) : ast_desc :=
  Ad_quote a_value b_value0.

Definition ad_list {A : Set} (function_parameter : A) : ast_desc :=
  let '_ := function_parameter in
  Ad_list Ad_None.

Definition quot_list {A B C : Set} (function_parameter : A)
  : B -> C -> ast_desc :=
  let '_ := function_parameter in
  fun (function_parameter : B) =>
    let '_ := function_parameter in
    fun (function_parameter : C) =>
      let '_ := function_parameter in
      Ad_None.

Definition process_ast_desc {A : Set} (function_parameter : A) : ast_desc :=
  let '_ := function_parameter in
  Ad_fixme Ad_FIXME_process_ast_desc.

Definition process_simple_ast_root (x_value : ast_desc) : ast_desc :=
  Ad_root x_value.

Definition process_string (a_value : ast_desc) : ast_desc :=
  quot Ad_process_string a_value.

Definition process_int (a_value : ast_desc) : ast_desc := Ad_int a_value.

Definition process_bool (a_value : ast_desc) : ast_desc := Ad_bool a_value.

Definition process_generic_list {A B C : Set}
  (name : A) (function_parameter : B) : C -> A :=
  let '_ := function_parameter in
  fun (function_parameter : C) =>
    let '_ := function_parameter in
    name.

Definition print_endline {A B : Set} (function_parameter : A) : B :=
  let '_ := function_parameter in
  op_startypeminuserrorstar.

Definition def_basic {A B : Set} (a_value : A) (b_value0 : B) : ast_desc :=
  my_append Ad_MetaCoq_Definition
    (my_append a_value
      (my_append Ad_TypeParam_T (my_append b_value0 Ad_Type_UUU))).

Definition def_pair {A B C D : Set}
  (a_value : A) (b_value0 : B) (a1 : C) (b1 : D) : ast_desc :=
  my_append Ad_Definition
    (my_append a_value
      (my_append Ad_TypeParam_T
        (my_append b_value0
          (my_append Ad_Type_UUU
            (my_append a1 (my_append Adxu (my_append b1 Ad_TypeParam_T_dot))))))).

Definition process_generic_type2 {A B C : Set} (function_parameter : A)
  : B -> C -> ast_desc :=
  let '_ := function_parameter in
  fun (function_parameter : B) =>
    let '_ := function_parameter in
    fun (function_parameter : C) =>
      let '_ := function_parameter in
      Ad_empty.

Definition not_empty {A B : Set} (function_parameter : A) : B :=
  let '_ := function_parameter in
  op_startypeminuserrorstar.

Definition ast_dest_list_to_single {A : Set} (function_parameter : A)
  : ast_desc :=
  let '_ := function_parameter in
  Ad_empty.

Definition process_ast_desc3 {A : Set} (function_parameter : A) : ast_desc :=
  let '_ := function_parameter in
  Ad_empty.

Definition process_ast_desc4 {A : Set} (function_parameter : A) : ast_desc :=
  let '_ := function_parameter in
  Ad_empty.

Definition process_ast_desc2 (function_parameter : ast_desc_list) : ast_desc :=
  match function_parameter with
  | Ad_empty_list => Ad_empty
  | Ad_cons _ t_value => op_startypeminuserrorstar
  end.

Definition process_root_list {A : Set} (a_value : A) : A := a_value.

Definition tostring {A : Set} (function_parameter : A) : ast_desc :=
  let '_ := function_parameter in
  Ad_todofixme.

Definition ast_desc_to_yojson {A : Set} (x_value : A) : A := x_value.

Definition process_generic_type_print {A B C D : Set} (function_parameter : A)
  : B -> C -> D :=
  let '_ := function_parameter in
  fun (function_parameter : B) =>
    let '_ := function_parameter in
    fun (c_value : C) =>
      let yj1 := process_root_list c_value in
      print_endline (my_append Ad_NEW yj1).

Definition process_generic_type {A B C : Set} (function_parameter : A)
  : B -> C -> ast_desc :=
  let '_ := function_parameter in
  fun (function_parameter : B) =>
    let '_ := function_parameter in
    fun (function_parameter : C) =>
      let '_ := function_parameter in
      Ad_None.

Definition process_structure_item (x_value : ast_desc) : ast_desc :=
  Ad_process_structure_item x_value.

Definition process_structure_item_desc (x_value : ast_desc) : ast_desc :=
  Ad_process_structure_item_desc x_value.

Definition extract_root (function_parameter : ast_desc) : ast_desc :=
  match function_parameter with
  | Ad_Ident string0 => Ad_Ident string0
  | Ad_bool bool0 => Ad_bool bool0
  | Ad_loc => process_generic_type3 Ad_ast_desc_Da Ad_Ad_loc_Da Ad_None
  | Ad_loc2 => process_generic_type3 Ad_ast_desc_Da Ad_Ad_loc2_Da Ad_None
  | Ad_loc_stack =>
    process_generic_type3 Ad_ast_desc_Da Ad_Ad_loc_stack_Da Ad_None
  | Ad_pos => process_generic_type3 Ad_ast_desc_Da Ad_Ad_pos_Da Ad_None
  | Ad_process_arg_constructor_declaration ast_desc0 =>
    process_generic_type3 Ad_ast_desc_Da
      Ad_Ad_process_arg_constructor_declaration_Da
      (Ad_process_ast_desc ast_desc0)
  | Ad_process_arg_label_expression ast_desc0 ast_desc1 =>
    process_generic_type3 Ad_ast_desc_Da Ad_Ad_process_arg_label_expression_Da
      (make_pair (process_ast_desc ast_desc0) (process_ast_desc ast_desc1))
  | Ad_process_arg_label_expression_list ast_desc0 =>
    process_generic_type3 Ad_ast_desc_Da
      Ad_Ad_process_arg_label_expression_list_Da (Ad_process_ast_desc ast_desc0)
  | Ad_process_ast_desc _ => Ad_Fixme2_Da
  | Ad_process_cases ast_desc0 =>
    process_generic_type3 Ad_ast_desc Ad_Ad_process_cases
      (Ad_process_ast_desc ast_desc0)
  | Ad_process_cstrs ast_desc0 =>
    process_generic_type3 Ad_ast_desc_Da Ad_Ad_process_cstrs_Da
      (Ad_process_ast_desc ast_desc0)
  | Ad_process_generic_list string0 _ =>
    process_generic_type3 Ad_ast_desc_Da Ad_Ad_process_generic_list_Da
      (make_pair (process_string string0) (Ad_fixme Ad_P4))
  | Ad_process_label_declaration_list _ => Ad_FIXME
  | Ad_process_list_tail ast_desc0 ast_desc1 =>
    process_generic_type3 Ad_ast_desc_Da Ad_Ad_process_list_tail_Da
      (make_pair (process_ast_desc ast_desc0) (process_ast_desc ast_desc1))
  | Ad_process_string_loc_list_pattern_option =>
    process_generic_type3 Ad_ast_desc_Da
      Ad_Ad_process_string_loc_list_pattern_option_Da Ad_None
  | Ad_process_value_binding_list =>
    process_generic_type3 Ad_ast_desc_Da Ad_Ad_process_value_binding_list_Da
      Ad_None
  | _ => Ad_Fixme1
  end.

Definition ff1 : ast_desc :=
  process_generic_type Ad_pattern_desc_Da Ad_Ppat_var_Da
    (string_value Ad_none_Da).

Definition ff0 : ast_desc :=
  process_generic_type Ad_rec_flag_Da Ad_Nonrecursive_Da Ad_None.

Definition ff00 : ast_desc := Ad_None.

Definition ff000 : ast_desc :=
  process_generic_type Ad_constant_Da Ad_Pconst_string_Da ff00.

Definition ff2 : ast_desc :=
  process_generic_type Ad_expression_desc_Da Ad_Pexp_constant_Da ff000.

Definition foo1 : ast_desc :=
  process_generic_type Ad_structure_item_desc_Da Ad_Pstr_value_Da
    (make_pair ff0 (make_pair ff1 ff2)).

Definition ref_air {A : Set} : A := op_startypeminuserrorstar.

Definition reifMyUU {A : Set} : A := op_startypeminuserrorstar.
