
Unimathcore_refl2_coq.vo:
	coqc   \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/Foundations/ UniMath.Foundations \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/Algebra/ UniMath.Algebra \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/CategoryTheory/ UniMath.CategoryTheory \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/Combinatorics/ UniMath.Combinatorics \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/Foundations/ UniMath.Foundations \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/MoreFoundations/ UniMath.MoreFoundations \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/NumberSystems/ UniMath.NumberSystems \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/OrderTheory/ UniMath.OrderTheory \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/PAdics/ UniMath.PAdics \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/SyntheticHomotopyTheory/ UniMath.SyntheticHomotopyTheory \
	  -R /mnt/data1/2024/01/05/UniMath/UniMath/Tactics/ UniMath.Tactics \
	 Unimathcore_refl2_coq.v 
